### ISSUE TITLE
作者您好，请问zh_vocab.txt在哪里能获取？谢谢！

### ISSUE THREAD

**Issue by begindadada** [yaoxiaoyuan/mimix#10]
在各个文件夹下没有找到zh_vocab.txt，请问zh_vocab.txt在哪里能获取，谢谢

**Comment by yaoxiaoyuan** [comment]
在model下有个文件夹vocab下载即可

**Comment by begindadada** [comment]
谢谢作者的回复，但是我们这边model下只有readme.txt这个文件诶，您可以再上传一次吗

**Comment by yaoxiaoyuan** [comment]
你要在百度网盘下的model下面去下载。

**Comment by begindadada** [comment]
噢噢找到了，谢谢谢谢！
