### ISSUE TITLE
做翻译时，有些特定内容会重复输出

### ISSUE THREAD

**Issue by heiheiheibj** [yaoxiaoyuan/mimix#16]
这个工具非常好使，不过发现一个问题
比如输入 “文心一言插件创意书、文心一言插件开发”
会变成这样

src:文心一言插件创意书、文心一言插件开发
--------------------
development development development development development development development development development development development development development development development development development development development development development development development development development development development development development development development development development development development development of the language of the language of the language,the language of the language of the language of the language of the language of the language of the language in the language of the language of the language plug plug plug plug plug plug plug plug plug plug plug plug plug development creative ideas,creative ideas,creative ideas,creative ideas books,creative ideas,creative ideas,creative ideas,creative ideas,creative ideas,creative ideas,creative ideas,creative ideas,creative ideas,creative ideas,creative ideas,creative ideas,creative ideas,creative ideas,creative ideas,creative ideas,creative ideas,wen heart,wen heart one word,wen heart one word,wen heart one word heart one word heart one word,wen heart heart one word,heart heart one word one word,heart heart one word,heart heart one word one word,heart heart one word one word,one word of one word of one language,one language of one language of the language plug plug plug plug plug plug plug plug plug plug plug plug plug plug plug plug plug plug plug plug plug plug plug plug plug plug plug plug plug plug -1.285689353942871
-----cost time: 10.966817140579224 s-----

![image](https://github.com/yaoxiaoyuan/mimix/assets/6910198/ea45724b-ba69-4df8-beba-0abc48e80694)

**Comment by heiheiheibj** [comment]
用的是 nmt_base_conf
谢谢

**Comment by yaoxiaoyuan** [comment]
前面带上_zhen_， 输入应该是_zhen_ + 空格 + 句子

**Comment by heiheiheibj** [comment]
非常感谢，疏忽大意了没加前缀。
