### ISSUE TITLE
MimixLM-0.7b-sft如何使用？

### ISSUE THREAD

**Issue by yyy40** [yaoxiaoyuan/mimix#20]
作者你好，MimixLM-0.7b-sft的详细使用能否说明一下，另外文档上说的chat.py并未找到。

异常：
![无标题](https://github.com/yaoxiaoyuan/mimix/assets/163929053/c26dc81c-1bea-416a-a030-3cc954845475)

**Comment by yaoxiaoyuan** [comment]
已经更新了代码，增加了chat.py。请再试试。
