### ISSUE TITLE
关于摘要生成中缺失的文件

### ISSUE THREAD

**Issue by HeroSong666** [yaoxiaoyuan/mimix#8]
作者大大您好，由于没有找到您的邮箱，所以就在这里给您留言了
我在使用中文摘要生成的功能时，程序显示需要一个文件zh_vocab.txt
请问可以分享一下吗？谢谢！

**Comment by yaoxiaoyuan** [comment]
你好，在model下面有一个vocab的文件夹需要下载即可。

**Comment by HeroSong666** [comment]
> 

感谢！

**Comment by begindadada** [comment]
> 你好，在model下面有一个vocab的文件夹需要下载即可。

没有这个文件夹诶，是不是被删了

**Comment by begindadada** [comment]
> > 
> 
> 感谢！

请问您找到这个zh_vocab.txt文件了吗，可以分享一下吗
